#Volume Setting Options:
#    LOW
#    MED
#    HIGH

# Intensity Setting Options:
#    LIGHT
#    LIGHTP  where 'P' stands for plus and indicates slight elevation in intensity compared to the regular setting
#    MOD
#    MODP
#    HEAVY
#    HEAVYP 
#    MAX

# INOL_Target Settings: 
#    Deload=0.4              #under 0.4 is too little for stimulating growth, but is perfect for deloading while still practicing skills
#    DailyRecoverable=0.8    #between 0.4 and 1.0 is recoverable stimulus (next day you can repeat the same workout basically)
#    LoadAccumulating=1.6    #1.0 to 2.0 is accumulating fatigue, with bigger strength gains (only once you fully recover, though)
                             #above 2.0 lies madness

Workoutdays: 
  - Day1:
    Name: Monday
    ExerciseList: ['snatch', 'snatch pull', 'snatch balance']
  - Day2:
    Name: Tuesday
    ExerciseList: ['clean', 'clean pull', 'front squat']
  - Day3:
    Name: Thursday
    ExerciseList: ['snatch', 'snatch pull', 'snatch balance']
  - Day4: 
    Name: Friday
    ExerciseList: ['jerk', 'push press', 'squat']

Weeks:
  - Week1:
    Volume: LOW
    Intensity: MODP
    INOL: DailyRecoverable
  - Week2:
    Volume: MED
    Intensity: MOD
    INOL: DailyRecoverable
  - Week3:
    Volume: MED
    Intensity: MODP
    INOL: DailyRecoverable
  - Week4:
    Volume: MEDP
    Intensity: MOD
    INOL: LoadAccumulating
